dogogram/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="django-admin"),

    path("", include(("posts.urls", "posts"), namespace="posts")),

    path("users/", include(("users.urls", "users"), namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path("", views.PostFeedView.as_view(), name="pretty_posts"),

    path(
        route="posts/new/", 
        view=views.CreatePostView.as_view(),
        name="new_post"),
    
    path(
        route="posts/like/<int:pk>/",
        view=views.PostUpdateView.as_view(),
        name="like"),

    path(
        route="posts/<int:pk>",
        view=views.PostDetailView.as_view(),
        name="detail"),

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from django.utils.html import mark_safe

# Create your models here.

class Post(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    profile = models.ForeignKey(Profile, on_delete=models.CASCADE)

    title = models.CharField(max_length=255)
    photo = models.ImageField(upload_to="posts/picture")

    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    likes = models.IntegerField(default=0)

    @property
    def thumbnail_preview(self):
        if self.photo:
            return mark_safe(f"<img src='{self.photo.url}' width='300px' height='300px'>")
        return ""

    def __str__(self):
        return f"{self.title} by {self.user.username}"

posts/views.py
# Posts's views

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from posts.form import PostsForm
from posts.models import Post
from users.models import FollowingFollowers
from django.shortcuts import redirect, render
from django.urls import reverse_lazy, reverse
from django.core.paginator import Paginator

# Create your views here.


class PostUpdateView(LoginRequiredMixin, UpdateView):

    queryset = Post.objects.all()
    fields = ["likes"]

    def get_object(self):
        obj = super().get_object()
        obj.likes += 1
        obj.save()
        return obj

    def render_to_response(self, context, **response_kwargs):
        return redirect(reverse("posts:pretty_posts")) # Redirije a la class view de para evitar la url


class CreatePostView(LoginRequiredMixin, CreateView):
    template_name = "posts/new.html"
    form_class = PostsForm
    success_url = reverse_lazy("posts:new_post")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["user"] = self.request.user
        context["profile"] = self.request.user.profile

        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    template_name = "posts/detail.html"
    queryset = Post.objects.all()
    context_object_name = "post"


class PostFeedView(LoginRequiredMixin, ListView):
    template_name = "posts/feed.html"
    model = Post
    paginate_by = 30
    context_object_name = "posts"

    def get_queryset(self):
        followers_list = FollowingFollowers.objects.filter(
            following_user=self.request.user)
        posts_lists = Post.objects.filter(user__in=[ u.follower_user for u in followers_list ]).order_by("-create_at")
        return posts_lists


########################################
# Esta es la versión View Function-base
#@@#####################################
# @login_required
# def prettier_post(request):
#     posts = Post.objects.all().order_by("-create_at")

#     return render(request, "posts/feed.html", {"posts":posts})


#####################################
# Esta es la creación de un post con 
# function view based
######################################
# @login_required
# def new_post(request):
#     if request.method == "POST":
#         form = PostsForm(request.POST, request.FILES)

#         if form.is_valid:
#             form.save()
#             return render(
#                 request,
#                 "posts/new.html",
#                 {
#                     "form": form,
#                     "user": request.user,
#                     "profile": request.user.profile,
#                     "is_valid": form.is_valid,
#                 }
#             )

#     else:
#         form = PostsForm()
    
#     return render(
#         request,
#         "posts/new.html",
#         {
#             "form": form,
#             "user": request.user,
#             "profile": request.user.profile,
#             "is_valid": form.is_valid,
#         }
#     )

templates/posts/detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Platzigram</title>
{% endblock%}
<!DOCTYPE html>
{% block container %}

    <div class="container">
        <div class="row">
            {% include "posts/post_card.html" %}
        </div>
    </div>

{% endblock %}

templates/posts/feed.html
{% extends "base.html" %}

    {% block head_content %}
        <title>Dogogram</title>
    {% endblock %}

        {% block container %}
        <div class="container" style="margin-top: 8em; margin-bottom: 2em;">
            {% for post in posts %}
                {% include "posts/post_card.html" %}
            {% endfor %}

        </div>

        {% include "pagination.html" %}
        {% endblock %}

templates/posts/new.html
{% extends "base.html" %}

{% block head_content %}
    <title>Create new post</title>
{% endblock %}

{% block container %}

    <div class="container">
        <div class="row justify-content-md-center">
            <div class="col-sm-12 col-md-8 col-lg-6 pt-2 px-5 pb-5" style="margin-top: 6em;" id="auth-container">
                {% if form.is_valid %}
                    <div class="alert alert-success mb-4">
                        The post were published succussefuly
                    </div>
                {% endif %}

                <h4 class="my-4">Post a new photo!</h4>

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    <input type="hidden" name="user" value="{{ user.pk }}" />
                    <input type="hidden" name="profile" value="{{ profile.pk }}" />
                    
                    {# Photo field #}
                    <div class="form-group">
                        <label>Choose your photo:</label>
                        <input
                        class="form-control {% if form.photo.errors %}is-invalid{% endif %}"
                        type="file"
                        name="photo"
                        placeholder="photo"
                        required
                        >
                        <div class="invalid-feedback">
                            {% for error in form.photo.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                    {# Title field #}
                    <div class="form-group">
                        <input
                            class="form-control {% if form.title.errors %}is-invalid{% endif %}"
                            type="text"
                            name="title"
                            placeholder="Title"
                            required
                        >
                        <div class="invalid-feedback">
                            {% for error in form.title.errors %}{{ error }}{% endfor %}
                        </div>
                    </div>
                    
                    <button type="submit" class="btn btn-primary btn-block mt-5">Publish!</button>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

templates/posts/post_card.html
<div class="col-sm-12 col-md-8 offset-md-2 mt-5 p-0" id="auth-container">
    <div class="media pt-3 pl-3 pb-1">
        <a href="{% url "users:detail" post.user.username %}">
            <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
        </a>
        <div class="media-body">
            <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
        </div>
    </div>

    <img style="width: 100%;" src="{{ post.photo.url }}" alt="{{ post.title }}">

    <p class="mt-2 ml-4" >
        <a href="{% url 'posts:like' post.pk %}" style="color: #000; font-size: 20px;">
            <i class="far fa-heart"></i>
        </a> {{ post.likes }}

    </p>
    <p class="ml-2 mt-0 mb-2 ml-4" style="width: auto;">
        <b>{{ post.title }}</b> - <small>{{ post.create_at }}</small>
    </p>
</div>

templates/posts/posts_detail.html
{% extends "base.html" %}

{% block head_content %}
    <title>Dogogram | {{ posts.user.username }}</title>
{% endblock %}

{% block container %}
<div class="card mb-3" style="max-width: 540px;">
    <div class="row no-gutters">
      <div class="col-md-4">
        <img src="..." class="card-img" alt="...">
      </div>
      <div class="col-md-8">
        <div class="card-body">
            <div class="border">
                <div class="media pt-3 pl-3 pb-1">
                    <a href="{% url "users:detail" posts.user.username %}">
                        <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                    </a>
                    <div class="media-body">
                        <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    </div>
                </div>
            </div>
            <div class="media pt-3 pl-3 pb-1">
                <a href="{% url "users:detail" post.user.username %}">
                    <img class="mr-3 rounded-circle" height="35" src="{{ post.profile.picture.url }}" alt="{{ post.user.get_full_name }}">
                </a>
                <div class="media-body">
                    <p style="margin-top: 5px;">{{ post.user.get_full_name  }}</p>
                    {{ posts.title }}
                </div>
            </div>
          <h5 class="card-title">Card title</h5>
          <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}