dogogram/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="django-admin"),

    path("", include(("posts.urls", "posts"), namespace="posts")),

    path("users/", include(("users.urls", "users"), namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path("", views.PostFeedView.as_view(), name="pretty_posts"),

    path(
        route="posts/new/", 
        view=views.CreatePostView.as_view(),
        name="new_post"),
    
    path(
        route="posts/like/<int:pk>/",
        view=views.PostUpdateView.as_view(),
        name="like"),

    path(
        route="posts/<int:pk>",
        view=views.PostDetailView.as_view(),
        name="detail"),

]

users/urls.py
# User's urls

from django.urls import path
from users import views

urlpatterns = [

    path(
        route="login/", 
        view=views.LoginView.as_view(),
        name="login"
    ),

    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name="logout"),

    path(
        route="signup",
        view=views.SignUpView.as_view(),
        name="signup"),

    path(
        route="me/profile",
        view=views.UpdateProfileView.as_view(),
        name="update"),

    path(
        route="follow/",
        view=views.FollowView.as_view(),
        name="follow"),

    path(
        route="unfollow/",
        view=views.UnfollowView.as_view(),
        name="unfollow"),

    path(
        route="<str:username>/",
        view=views.UserDetailView.as_view(),
        # view=TemplateView.as_view(template_name="users/detail.html"), # Una clase solo para mostrar un template
        name="detail"
    ),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}


    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <script src="https://kit.fontawesome.com/5121e23a1c.js" crossorigin="anonymous"></script>
    <script async src='/cdn-cgi/bm/cv/669835187/api.js'></script>
</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script type="text/javascript">(function(){window['__CF$cv$params']={r:'61d9927a3df53708',m:'f324b7a6aae9357dae5e317a35ac6ffb30af11dc-1612663802-1800-AX15z9VF3emFCfacvIv44NFe5sq1KWFURq3HVdpkdp3oPAu4i6c1CAwLf+z1DF9RvJLniH9Ro9wG4wEsrF8KfkDyI/QdJweD7x72mwVJqoeso93Xn3mOql9DQ1Ofq5CTuRtAy0bkcaOLeY12OF8UGRqbGuT50ewZz4oD7kC8iA6Eo6/JJoC7klriheZI/ijxR3/DsQa0oRNyPixBRkYQdisuZFp7uBdD7wjGQsvey9CdeewGPM6xWhrk1NYHFSWBAA==',s:[0x561cbd21f5,0x870309a495],}})();</script>
</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">
        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:pretty_posts' %}">
            <img src="{% static 'img/dogogram_logo.png' %}" height="45" class="d-inline-block align-top"/>
        </a>
        <button class="navbar-toggler border" type="button" data-toggle="collapse" data-target="#navbarContent" aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
            <span>
                <i class="fas fa-bars"></i>
            </span>
        </button>
        <div class="collapse navbar-collapse" id="navbarContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a href="{% url 'users:detail' request.user.username %}">
                        {% if request.user.profile.picture %}
                            <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:new_post' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>
                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Previous
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="page-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Next
            </a>
        </li>
        {% endif %}
    </ul>
</nav>