dogogram/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls, name="django-admin"),

    path("", include(("posts.urls", "posts"), namespace="posts")),

    path("users/", include(("users.urls", "users"), namespace="users")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from posts import views

urlpatterns = [
    path("", views.PostFeedView.as_view(), name="pretty_posts"),

    path(
        route="posts/new/", 
        view=views.CreatePostView.as_view(),
        name="new_post"),
    
    path(
        route="posts/like/<int:pk>/",
        view=views.PostUpdateView.as_view(),
        name="like"),

    path(
        route="posts/<int:pk>",
        view=views.PostDetailView.as_view(),
        name="detail"),

]

users/urls.py
# User's urls

from django.urls import path
from users import views

urlpatterns = [

    path(
        route="login/", 
        view=views.LoginView.as_view(),
        name="login"
    ),

    path(
        route="logout",
        view=views.LogoutView.as_view(),
        name="logout"),

    path(
        route="signup",
        view=views.SignUpView.as_view(),
        name="signup"),

    path(
        route="me/profile",
        view=views.UpdateProfileView.as_view(),
        name="update"),

    path(
        route="follow/",
        view=views.FollowView.as_view(),
        name="follow"),

    path(
        route="unfollow/",
        view=views.UnfollowView.as_view(),
        name="unfollow"),

    path(
        route="<str:username>/",
        view=views.UserDetailView.as_view(),
        # view=TemplateView.as_view(template_name="users/detail.html"), # Una clase solo para mostrar un template
        name="detail"
    ),

]

users/models.py
# Users models

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # para que herede del model User de Django

    website = models.URLField(max_length=200, blank=True)
    bio = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)
    picture = models.ImageField(upload_to="users/pictures", blank=True, null=True)

    create_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username


class FollowingFollowers(models.Model):
    
    following_user = models.ForeignKey(User, related_name="following", on_delete=models.CASCADE, null=True)

    follower_user = models.ForeignKey(User, related_name="followers", on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.following_user} follows {self.follower_user}"

users/forms.py
# Users Forms

from django.forms import ModelForm
from users.models import FollowingFollowers

class FollowForm(ModelForm):
    class Meta:
        model = FollowingFollowers
        fields = ["following_user", "follower_user"]

users/views.py
# Users's views

# Django
from django.db.models import Q
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth import views as auth_views
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, FormView, UpdateView, CreateView, DeleteView

# Dogogram
from posts.models import Post
from dogogram.forms import SignUpForm
from users.forms import FollowForm
from users.models import Profile, FollowingFollowers

# Create your views here.


class UnfollowView(LoginRequiredMixin, DeleteView):
    template_name =  "users/unfollow.html"
    model = FollowingFollowers
    form_class = FollowForm

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        follower_user_pk = self.request.POST["follower_user"]
        self.follower_user = User.objects.filter(pk=follower_user_pk).first()
        self.follower_username = self.follower_user.username

    def get_object(self):
        unfollow_obj = FollowingFollowers.objects.get(
            Q(following_user=self.request.user) & Q(follower_user=self.follower_user)
        )
        return unfollow_obj

    def get_success_url(self):
        username = self.follower_username
        return reverse('users:detail', kwargs={'username': username})


class FollowView(LoginRequiredMixin, CreateView):
    template_name = "users/follow.html"
    model = FollowingFollowers
    form_class = FollowForm

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        follower_user_pk = self.request.POST["follower_user"]
        follower_user = User.objects.filter(pk=follower_user_pk).first()
        self.follower_username = follower_user.username

    def get_success_url(self):
        username = self.follower_username
        return reverse('users:detail', kwargs={'username': username})


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update.html'
    model = Profile
    fields = ['website', 'bio', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})


class UserDetailView(LoginRequiredMixin, DetailView):
    
    template_name = "users/detail.html"
    slug_field = "username"
    slug_url_kwarg = "username"
    queryset = User.objects.all()
    context_object_name = "user"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.get_object()
        context["posts"] = Post.objects.filter(user=user).order_by("-create_at")
        friend = FollowingFollowers.objects.filter(
            following_user=self.request.user
        ).filter(
            follower_user=context["user"]
        )
        if friend:
            context["is_friend"] = True
        return context


class SignUpView(FormView):
    template_name = "users/signup.html"
    form_class = SignUpForm
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class LoginView(auth_views.LoginView):

    template_name = "users/login.html"
    redirect_authenticated_user = True # Evita que el usuario ya logado vuelva a la pagina de login


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    pass
    
    # next_page = reverse("users:login")


#########################################
# Esta es la function view para el log out
#########################################
# @login_required
# def dogo_logout(request):
#     logout(request)
#     return redirect("users:login")


#########################################
# Esta es la function view para el log in
#########################################
# def dogo_login(request):
    
#     if request.method == "POST":
        
#         username = request.POST["username"]
#         password = request.POST["password"]
#         user = authenticate(request, username=username, password=password)
#         if user is not None:
#             login(request, user)
#             return redirect("posts:pretty_posts")
#         else:
#             return render(request, "users/login.html", {"error":"Invalid username or password"})
    
#     return render(request, "users/login.html")


#########################################
# Esta es la function view para sign up
#########################################
# def dogo_signup(request):

#     if request.method == 'POST':
#         form = SignUpForm(request.POST)
#         if form.is_valid():
#             form.save()
#             redirect("users:signup")

#     else:
#         form = SignUpForm()

#     return render(request, "users/signup.html", { "form": form })


###################################
# Actualizar el perfil de usuario
# en Function View
###################################
# @login_required
# def dogo_update_profile(request):
#     profile = request.user.profile

#     if request.method == "POST":
#         form = UpdateForm(request.POST, request.FILES)

#         if form.is_valid():
#             data = form.cleaned_data
#             profile.website = data["website"]
#             profile.bio = data["bio"]
#             profile.picture = data["picture"]
#             profile.phone_number = data["phone_number"]
#             profile.save()
            
#             url = reverse("users:login")
#             redirect(url)
        
#     else:
#         form = UpdateForm()

#     return render(
#         request,
#         "users/update.html",
#         { 
#             "profile":profile,
#             "form":form,
#         })

templates/users/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

    <script async src='/cdn-cgi/bm/cv/669835187/api.js'></script>
</head>
<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">
                <a href="{% url 'posts:pretty_posts' %}">
                    <img src="{% static 'img/dogogram_logo.png' %}" class="img-fluid rounded mx-auto d-block pb-4 mt-4" style="max-width: 60%;">
                </a>

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script type="text/javascript">(function(){window['__CF$cv$params']={r:'61e6c3606b3d371e',m:'77525350bbe5cbf544d8abd126dfe72948281242-1612802120-1800-AWvSGNtIU+3RDZAuYw0Kbh4z1NIoLRrrurl4ZSliGmil/PXlyyl4dqAaOhkgZ7qVFZSxcl5MtIHMkMQxrcdMhAeyojCsO2agqWCfE0xfBQSmvc+cfVrsnQ2BPq02ztxt2o9NwwbD3iTGd9PA5wLK8UfEmsPC2U2cGlOx/6OcNAbRh1198Jd6qp+HtDZ96XRFMcqB5KHC3y5KQOKAyWrXjbcU+bTIQ2bbynz6qGe7GDSlPsUMSWljsPvG6fsN5MXcUA==',s:[0x7f193a593d,0x9c44c48dcb],}})();</script>
</body>
</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

    <div class="container mb-5" style="margin-top: 8em;">
        <div class="row">
            <div class="col-sm-4 d-flex justify-content-center">
                <img src="{{ user.profile.picture.url }}" alt="@{{ user.username }}" class="rounded-circle" width="150px" />
            </div>
            <div class="col-sm-8">
                <h2 style="font-weight: 100;">
                    <div class="d-flex flex-row">
                        {{ user.username }}
                        {% if user == request.user %}
                            <a href="{% url "users:update" %}" class="ml-5 btn btn-sm btn-outline-info">
                                Edit profile
                            </a>
                        {% elif is_friend %}
                            <form action="{% url 'users:unfollow' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="following_user" value="{{ request.user.pk }}">
                                <input type="hidden" name="follower_user" value="{{ user.pk }}">
                                <input type="submit" class="ml-5 btn btn-sm btn-danger" value="Unfollow">
                            </form>
                        {% else %}
                            <form action="{% url 'users:follow' %}" method="POST">
                                {% csrf_token %}
                                <input type="hidden" name="following_user" value="{{ request.user.pk }}">
                                <input type="hidden" name="follower_user" value="{{ user.pk }}">
                                <input type="submit" class="ml-5 btn btn-sm btn-primary" value="Follow">
                            </form>
                        {% endif %}
                    </div>
                </h2>
                <div class="row mt-2" style="font-size: 1.2em">
                    <div class="col-sm-4">
                        <b>{{ posts.count }}</b> posts
                    </div>
                    <div class="col-sm-4">
                        <b>
                            {% if user.followers.count > 0 %}
                                {{ user.followers.count }}
                            {% else %}
                                0
                            {% endif %}
                        </b> followers
                    </div>
                    <div class="col-sm-4">
                        <b>
                            {% if user.following.count > 0 %}
                                {{ user.following.count }}
                            {% else %}
                                0
                            {% endif %}
                        </b> following
                    </div>
                </div>
                <div class="row mt-4">
                    <div class="col-sm-12">
                        <p>{{ user.profile.bio }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <hr>
    {# Show user's posts #}
    <div class="container" id="user-posts">
        <div class="row mt-3">
            {% for post in posts %}
            <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
                <a href="{% url 'posts:detail' post.pk %}" class="border">
                    <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid"/>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Dogogram | Sign in</title>
{% endblock %}

{% block container %}

    {% if form.errors %}
        <p class="alert alert-danger alert-dismissible fade show" role="alert">
            The username or password didn't match. Please try again.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </p>
    {% endif %}

    <form action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" id="username" aria-describedby="emailHelp" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary btn-block mt-5" id="btn-gradient">Submit</button>
    </form>

    <p class="mt-4">You don't have an account yet? <a href="{% url 'users:signup' %}">Sign up here</a></p>
{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Platzigram | Sign up</title>
{% endblock %}

{% block container %}

    <form action="{% url 'users:signup' %}" method="POST">
        {% csrf_token %}

        <h3 class="text-muted mb-4">Sign In</h3>

        {{ form.as_p }}

        <button class="btn btn-primary btn-block mt-5" type="submit">Register!</button>

    </form>

{% endblock %}

templates/users/update.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
    <title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" style="margin-top: 6em;" id="auth-container">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="media">
                    {% if profile.picture %}
                        <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                        <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4">
                            <input type="file" name="picture">
                            {% if form.picture.errors %}
                                <div class="alert alert-danger">
                                    {% for error in form.picture.errors%}
                                        <b>Picture</b>: {{ error }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </p>
                    </div>
                </div>

                <hr><br>

                <div class="form-group">
                    <label>Website</label>
                    <input
                        class="form-control {% if form.website.errors %} is-invalid {% endif %}"
                        type="text"
                        name="website"
                        placeholder="Website"
                        value="{% if form.website.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                    />
                        <div class="invalid-feedback">
                            {% for error in form.website.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                </div>

                <div class="form-group">
                    <label>Biography</label>
                        <textarea class="form-control {% if form.bio.errors %}is-invalid{% endif %}" 
                            placeholder="Write something about you..." 
                            name="bio">{% if form.bio.errors %}{{ form.bio.value }}{% else %}{{ profile.bio }}{% endif %}</textarea>
                        <div class="invalid-feedback">
                            {% for error in form.bio.errors %}
                                {{ error }}
                            {% endfor %}
                        </div>
                </div>

                <div class="form-group">
                    <label>Phone number</label>
                    <input
                        class="form-control {% if form.phone_number.errors %} is-invalid {% endif %}"
                        type="text"
                        name="phone_number"
                        placeholder="Phone number"
                        value="{{ profile.phone_number }}"
                    />
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}